### ISSUE TITLE
Version information missing

### ISSUE THREAD

**Issue by krakjoe** [php-ds/docs#1]
https://github.com/php-ds/docs/blob/master/docs/versions.xml

Look at another extension for reference.

**Comment by rtheunissen** [comment]
Will do, only the initial boilerplate so far. An attempt, anyway.

**Comment by rtheunissen** [comment]
Currently at `PHP 7, ds >= 1.0.0`.

**Comment by rtheunissen** [comment]
`PECL ds >= 1.0.0`
