### ISSUE TITLE
Methods missing in class synopsis

### ISSUE THREAD

**Issue by rtheunissen** [php-ds/docs#4]
It appears that methods that are implemented according to an interface don't show up in the class synopsis. Here is the error I get during build:

```
XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook)
 xpointer(id('class.ds-deque')/db:refentry/db:refsect1[@role='description']/descendant::db:methodsynopsis[not(@role='procedural')])
```

And the result is:
<img width="346" alt="screen shot 2016-07-28 at 1 21 21 am" src="https://cloud.githubusercontent.com/assets/809191/17177495/c8bffd14-5465-11e6-8e74-1d959407ab9f.png">

**Comment by rtheunissen** [comment]
@salathe I've been told that you are the best person to ask about this. Is this expected behaviour?

**Comment by alfsb** [comment]
On Mon, Aug 1, 2016 at 12:53 PM, Rudi Theunissen
> Also, while Vector::copy() returns a Vector, the Collection interface requires that Collection be the return type. I couldn't get it to work that it's enforced by the base interface while also using self as the return type. 

This on PHP code or in manual?

**Comment by rtheunissen** [comment]
Code. Manual should be easy.

**Comment by alfsb** [comment]
One suggestion: use the manual XML as source.

DocBook is highly structured, and there is so much information in classsynopsis (oointerface/interfacename) of ds docs and it's interfaces (methodsysnopsis below interface XML IDs) it would be possible to generate new documentation from existing documentation.

The xinclude/xpointer it's just a crude variation of this process.

**Comment by rtheunissen** [comment]
@alfsb so use existing documentation (such as the methods in Sequence) to generate the docs for its implementations, via linking? My plan for today was to manually copy and adjust all the Sequence methods into both Deque and Vector, even though it would introduce a lot of redundancy and duplication. 

I'm not familiar enough with docbook yet to clearly see how reuse would work, but I'll spend some time on it today and see how far I get. Will commit something in the meantime though to get rid of the build errors and missing methods on php.net

**Comment by alfsb** [comment]
Not via linking, but via copy/duplication. Instead of manually duplicating the files, inspect tags below IDs from the interfaces to create adjusted files below Deque and Vector.

Linking (or copy by xinclude) does not work because they don't change tags. It's necessary to alter returns and class names, and so generate the a lot of "duplicated" files, not identical of the interfaces.

At least for method signatures (methodsynopsis tag). Textual descriptions need be checked in each case. E.g., resize behavior. See my last commit hours ago.

**Comment by rtheunissen** [comment]
I have no added and checked all missing methods. This resolves the XPointer evaluation error, and the docs are now more usable (at the cost of duplication in the XML).

Thanks for your help @alfsb ✨
